/**
 * Каталог методов уникализации: метаданные для UI и рекомендуемые значения.
 */

const METHOD_CATALOG = [
  {
    key: 'crop',
    label: 'Обрезка',
    tooltip: 'Случайная обрезка краёв кадра — меняет композицию для хешей.',
    params: {
      cropMaxPct: { type: 'number', min: 0.5, max: 5, step: 0.1, label: 'Макс. % обрезки' },
    },
  },
  {
    key: 'rotate',
    label: 'Поворот',
    tooltip: 'Лёгкий поворот с обрезкой до исходного размера.',
    params: {
      rotateMaxDeg: { type: 'number', min: 0.5, max: 5, step: 0.1, label: 'Макс. угол °' },
    },
  },
  {
    key: 'hflip',
    label: 'Зеркало',
    tooltip: 'Горизонтальное отражение — сильный сбой для нейросетей.',
    params: {},
  },
  {
    key: 'speed',
    label: 'Скорость',
    tooltip: 'Изменение скорости воспроизведения через setpts/atempo.',
    params: {
      speedMin: { type: 'number', min: 0.9, max: 1.1, step: 0.01, label: 'Мин. скорость' },
      speedMax: { type: 'number', min: 0.9, max: 1.1, step: 0.01, label: 'Макс. скорость' },
    },
  },
  {
    key: 'color',
    label: 'Цветокоррекция',
    tooltip: 'Глобальная коррекция всего кадра: баланс белого, яркость, контраст, насыщенность, оттенок.',
    params: {
      brightnessMin: { type: 'number', min: -0.2, max: 0.2, step: 0.01, label: 'Яркость мин.' },
      brightnessMax: { type: 'number', min: -0.2, max: 0.2, step: 0.01, label: 'Яркость макс.' },
      contrastMin: { type: 'number', min: 0.5, max: 1.5, step: 0.01, label: 'Контраст мин.' },
      contrastMax: { type: 'number', min: 0.5, max: 1.5, step: 0.01, label: 'Контраст макс.' },
      saturationMin: { type: 'number', min: 0.5, max: 1.5, step: 0.01, label: 'Насыщ. мин.' },
      saturationMax: { type: 'number', min: 0.5, max: 1.5, step: 0.01, label: 'Насыщ. макс.' },
      hueMin: { type: 'number', min: -30, max: 30, step: 0.5, label: 'Оттенок мин. °' },
      hueMax: { type: 'number', min: -30, max: 30, step: 0.5, label: 'Оттенок макс. °' },
      colorBalanceMax: { type: 'number', min: 0, max: 0.2, step: 0.01, label: 'Баланс ±' },
    },
  },
  {
    key: 'noise',
    label: 'Шум',
    tooltip: 'Пиксельный шум поверх кадра.',
    params: {
      noiseMin: { type: 'number', min: 1, max: 30, step: 1, label: 'Шум мин.' },
      noiseMax: { type: 'number', min: 1, max: 30, step: 1, label: 'Шум макс.' },
    },
  },
  {
    key: 'vignette',
    label: 'Виньетка',
    tooltip: 'Затемнение углов кадра.',
    params: {},
  },
  {
    key: 'blur',
    label: 'Размытие',
    tooltip: 'Лёгкий unsharp/smartblur.',
    params: {
      blurSigmaMin: { type: 'number', min: 0.1, max: 3, step: 0.1, label: 'Sigma мин.' },
      blurSigmaMax: { type: 'number', min: 0.1, max: 3, step: 0.1, label: 'Sigma макс.' },
    },
  },
  {
    key: 'resample',
    label: 'Ресэмпл',
    tooltip: 'Уменьшение и обратное масштабирование.',
    params: {
      resampleMin: { type: 'number', min: 0.9, max: 1, step: 0.01, label: 'Scale мин.' },
      resampleMax: { type: 'number', min: 0.9, max: 1, step: 0.01, label: 'Scale макс.' },
    },
  },
  {
    key: 'encode',
    label: 'Кодирование',
    tooltip: 'Случайный CRF и GOP при перекодировании.',
    params: {
      crfMin: { type: 'number', min: 15, max: 30, step: 1, label: 'CRF мин.' },
      crfMax: { type: 'number', min: 15, max: 30, step: 1, label: 'CRF макс.' },
      gopMin: { type: 'number', min: 12, max: 240, step: 1, label: 'GOP мин.' },
      gopMax: { type: 'number', min: 12, max: 240, step: 1, label: 'GOP макс.' },
    },
  },
  {
    key: 'trim',
    label: 'Обрезка начала',
    tooltip: 'Удаление первых кадров с начала видео.',
    params: {
      trimFramesMin: { type: 'number', min: 1, max: 10, step: 1, label: 'Кадров мин.' },
      trimFramesMax: { type: 'number', min: 1, max: 10, step: 1, label: 'Кадров макс.' },
    },
  },
  {
    key: 'audio',
    label: 'Аудио',
    tooltip: 'Громкость, задержка, сдвиг тона, эквалайзер и частота дискретизации.',
    params: {
      volumeMin: { type: 'number', min: 0.5, max: 1.5, step: 0.01, label: 'Громк. мин.' },
      volumeMax: { type: 'number', min: 0.5, max: 1.5, step: 0.01, label: 'Громк. макс.' },
      audioDelayMax: { type: 'number', min: 0, max: 500, step: 10, label: 'Задержка ± ms' },
      pitchMin: { type: 'number', min: 0.95, max: 1.05, step: 0.001, label: 'Тон мин.' },
      pitchMax: { type: 'number', min: 0.95, max: 1.05, step: 0.001, label: 'Тон макс.' },
      eqFrequencyMin: { type: 'number', min: 200, max: 8000, step: 100, label: 'EQ част. мин. Hz' },
      eqFrequencyMax: { type: 'number', min: 200, max: 8000, step: 100, label: 'EQ част. макс. Hz' },
      eqGainMin: { type: 'number', min: -6, max: 6, step: 0.5, label: 'EQ gain мин. dB' },
      eqGainMax: { type: 'number', min: -6, max: 6, step: 0.5, label: 'EQ gain макс. dB' },
      sampleRateMin: { type: 'number', min: 44100, max: 48000, step: 1000, label: 'Sample rate мин.' },
      sampleRateMax: { type: 'number', min: 44100, max: 48000, step: 1000, label: 'Sample rate макс.' },
    },
  },
  {
    key: 'watermark',
    label: 'Watermark',
    tooltip: 'Полупрозрачная метка времени.',
    params: {},
  },
  {
    key: 'fade',
    label: 'Fade',
    tooltip: 'Плавное появление и затухание.',
    params: {
      fadeMin: { type: 'number', min: 0.05, max: 2, step: 0.05, label: 'Fade мин. с' },
      fadeMax: { type: 'number', min: 0.05, max: 2, step: 0.05, label: 'Fade макс. с' },
    },
  },
  {
    key: 'remux',
    label: 'Remux',
    tooltip: 'Faststart после кодирования.',
    params: {},
  },
  {
    key: 'movingOverlay',
    label: 'Движ. объекты',
    tooltip: 'Полупрозрачные движущиеся объекты — сбивают perceptual hash.',
    params: {
      overlayCount: { type: 'number', min: 1, max: 3, step: 1, label: 'Кол-во объектов' },
      overlayOpacity: { type: 'number', min: 0.05, max: 0.5, step: 0.05, label: 'Прозрачность' },
      overlaySpeed: { type: 'number', min: 20, max: 200, step: 10, label: 'Скорость' },
    },
  },
  {
    key: 'fpsJitter',
    label: 'FPS jitter',
    tooltip: 'Смена временной сетки кадров (29.97 ↔ 30), меняет GOP.',
    params: {
      fpsJitterPts: { type: 'number', min: 1.0001, max: 1.01, step: 0.0001, label: 'Множитель PTS' },
    },
  },
];

const MODERATE_DEFAULTS = {
  cropMaxPct: 1.5,
  rotateMaxDeg: 2,
  speedMin: 0.98,
  speedMax: 1.02,
  brightnessMin: -0.12,
  brightnessMax: 0.12,
  contrastMin: 0.88,
  contrastMax: 1.12,
  saturationMin: 0.88,
  saturationMax: 1.12,
  hueMin: -12,
  hueMax: 12,
  colorBalanceMax: 0.12,
  noiseMin: 5,
  noiseMax: 15,
  crfMin: 20,
  crfMax: 24,
  gopMin: 24,
  gopMax: 120,
  blurSigmaMin: 0.5,
  blurSigmaMax: 1.0,
  resampleMin: 0.97,
  resampleMax: 0.99,
  trimFramesMin: 1,
  trimFramesMax: 3,
  volumeMin: 0.85,
  volumeMax: 1.15,
  audioDelayMax: 100,
  pitchMin: 0.96,
  pitchMax: 1.04,
  eqFrequencyMin: 800,
  eqFrequencyMax: 3000,
  eqGainMin: -4,
  eqGainMax: 4,
  sampleRateMin: 44100,
  sampleRateMax: 48000,
  fadeMin: 0.2,
  fadeMax: 0.5,
  overlayCount: 2,
  overlayOpacity: 0.15,
  overlaySpeed: 100,
  fpsJitterPts: 1.001,
};

const MAXIMUM_DEFAULTS = {
  cropMaxPct: 3.0,
  rotateMaxDeg: 2,
  speedMin: 0.95,
  speedMax: 1.05,
  brightnessMin: -0.18,
  brightnessMax: 0.18,
  contrastMin: 0.85,
  contrastMax: 1.18,
  saturationMin: 0.85,
  saturationMax: 1.18,
  hueMin: -18,
  hueMax: 18,
  colorBalanceMax: 0.15,
  noiseMin: 5,
  noiseMax: 20,
  crfMin: 18,
  crfMax: 24,
  gopMin: 24,
  gopMax: 120,
  blurSigmaMin: 0.5,
  blurSigmaMax: 1.5,
  resampleMin: 0.95,
  resampleMax: 0.98,
  trimFramesMin: 1,
  trimFramesMax: 5,
  volumeMin: 0.8,
  volumeMax: 1.2,
  audioDelayMax: 150,
  pitchMin: 0.94,
  pitchMax: 1.06,
  eqFrequencyMin: 500,
  eqFrequencyMax: 5000,
  eqGainMin: -6,
  eqGainMax: 6,
  sampleRateMin: 44100,
  sampleRateMax: 48000,
  fadeMin: 0.2,
  fadeMax: 0.6,
  overlayCount: 3,
  overlayOpacity: 0.2,
  overlaySpeed: 120,
  fpsJitterPts: 1.001,
};

function getRecommendedDefaults(maxMode) {
  return maxMode ? { ...MAXIMUM_DEFAULTS } : { ...MODERATE_DEFAULTS };
}

module.exports = {
  METHOD_CATALOG,
  MODERATE_DEFAULTS,
  MAXIMUM_DEFAULTS,
  getRecommendedDefaults,
};
